const dataProducts = [
  {
    id: 1,
    name: 'Smartphone',
    price: 599.99,
    category: 'Electronics',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 2,
    name: 'Laptop',
    price: 999.99,
    category: 'Electronics',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 3,
    name: 'Coffee Maker',
    price: 49.99,
    category: 'Kitchen Appliances',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 4,
    name: 'Desk Chair',
    price: 149.99,
    category: 'Furniture',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 5,
    name: 'Bluetooth Speaker',
    price: 69.99,
    category: 'Electronics',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 6,
    name: 'Digital Camera',
    price: 399.99,
    category: 'Electronics',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 7,
    name: 'Microwave Oven',
    price: 129.99,
    category: 'Kitchen Appliances',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 8,
    name: 'Running Shorts',
    price: 29.99,
    category: 'Clothing ',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 9,
    name: 'Gaming Console',
    price: 499.99,
    category: 'Electronics',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
  {
    id: 10,
    name: 'Coffee Table',
    price: 199.99,
    category: 'Electronics',
    image: 'https://source.unsplash.com/random/200x200',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa iusto aliquam expedita dolorum ipsa placeat error illum nam. Reiciendis, fuga earum. Repellat consequuntur ipsam aut repellendus sequi dolore nam explicabo modi, debitis laudantium voluptate autem dicta repudiandae exercitationem natus excepturi beatae asperiores saepe? Voluptas maxime eum eligendi aut sapiente?',
  },
]

export default dataProducts
